name: Build, test

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        package: [sn-filter-pane, sn-listbox]
    uses: ./.github/workflows/build-test-single.yml
    with:
      package: ${{ matrix.package }}
  coverage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          path: coverage
      - name: Combine test reports and publish to Code Climate
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: |
          ./test/bin/cc-test-reporter sum-coverage ./coverage/artifact/codeclimate.*.json -p 2 -o coverage/codeclimate.summed.json
          ./test/bin/cc-test-reporter upload-coverage -i ./coverage/codeclimate.summed.json
