name: Build single

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string

defaults:
  run:
    working-directory: packages/${{ inputs.package }}

jobs:
  build-package:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: npm build in ${{ inputs.package }}
      run: |
        npm ci
        npm run build
        npm run lint
        npm run test
