name: Build single

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string

jobs:
  build-package:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'yarn'
        cache-dependency-path: packages/${{ inputs.package }}/yarn.lock

    - name: build in ${{ inputs.package }}
      working-directory: packages/${{ inputs.package }}
      run: |
        yarn install --immutable --immutable-cache --check-cache
        yarn build

    - name: lint
      working-directory: packages/${{ inputs.package }}
      run: yarn run lint

    - name: types
      working-directory: packages/${{ inputs.package }}
      run: yarn types:check

    - name: test
      working-directory: packages/${{ inputs.package }}
      run: |
        yarn run test --maxWorkers=2 --coverage
        ../../test/bin/cc-test-reporter format-coverage -t lcov -o ../../coverage/codeclimate.${{ inputs.package }}.json ../packages/${{ inputs.package }}/coverage/lcov.info

    - uses: actions/upload-artifact@v4
      with:
        path: coverage/codeclimate.${{ inputs.package }}.json
