name: Build, test

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        package: [sn-filter-pane, sn-listbox]
    uses: qlik-oss/sn-list-objects/.github/workflows/build-test-single.yml@main
    with:
      package: ${{ matrix.package }}
