name: Build single

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string

jobs:
  build-package:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'yarn'
        cache-dependency-path: packages/${{ inputs.package }}/yarn.lock

    - name: build in ${{ inputs.package }}
      working-directory: packages/${{ inputs.package }}
      run: |
        yarn install --immutable --immutable-cache --check-cache
        yarn build

    - name: lint
      working-directory: packages/${{ inputs.package }}
      run: yarn run lint

    - name: test
      working-directory: packages/${{ inputs.package }}
      run: yarn run test

    - name: rendering
      working-directory: packages/${{ inputs.package }}
      runs-on: ubuntu-latest
      steps:
        - run: yarn playwright install --with-deps
        - run: yarn run test:rendering
          id: rendering
          with:
            name: rendering-output
            path: |
              test/rendering/reports/html/
              test-results/
            retention-days: 3