name: Build, test

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        package: [sn-filter-pane, sn-listbox]
    uses: qlik-oss/sn-list-objects/.github/workflows/build-test-single.yml@main
    with:
      package: ${{ matrix.package }}
  validate:
    runs-on: ubuntu-latest
    steps:
      - run: yarn playwright install --with-deps
      - run: yarn run test:rendering
        id: rendering
        with:
          name: rendering-output
          path: |
            test/rendering/reports/html/
            test-results/
          retention-days: 3
