name: Build, test

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        package: [sn-filter-pane, sn-listbox]
    uses: qlik-oss/sn-list-objects/.github/workflows/build-test-single.yml@main
    with:
      package: ${{ matrix.package }}

  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: yarn
      - name: build filterpane
        working-directory: packages/sn-filter-pane
        run: |
          yarn
          yarn build
      - run: yarn playwright install --with-deps
      - run: yarn run test:rendering
        id: rendering
      - uses: actions/upload-artifact@v3
        if: ${{ failure() && steps.rendering.conclusion == 'failure' }}
        with:
          name: rendering-report
          path: test/rendering/reports/html/
          retention-days: 3
      - uses: actions/upload-artifact@v3
        if: ${{ failure() && steps.rendering.conclusion == 'failure' }}
        with:
          name: rendering-output
          path: test-results/
          retention-days: 3
