# Run on a branch to update rendering test snapshots
name: Update Snapshots [Experimental]
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-snapshots:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_BUILD }}
      - uses: actions/setup-node@v4
      - run: yarn
      - name: build filterpane
        working-directory: packages/sn-filter-pane
        run: |
          yarn
          yarn build
      - run: yarn playwright install --with-deps
      - run: yarn run test:rendering --update-snapshots
      - run: yarn run test:integration --update-snapshots
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'test: update rendering test screenshots'

